### ISSUE TITLE
UI: 類似度を比較するフレームワークを増やしすぎると表示が潰れる

### ISSUE THREAD

**Issue by KoichiKiyokawa** [KoichiKiyokawa/tech-choice#29]
![image](https://user-images.githubusercontent.com/40315079/134111016-94f84eb5-954c-4270-9521-a4b4d6f65bba.png)

↓みたいなCSSで`min-width`を指定すると、headerとbodyがずれて表示されてしまう。
```css
.container.container.container :global(.bx--data-table--sticky-header th),
.container.container.container :global(.bx--data-table--sticky-header td) {
  min-width: 170px;
}
```
